### ISSUE TITLE
Browser Fails to run on RPi.

### ISSUE THREAD

**Issue by Ovalelephant35** [sugarlabs/browse-activity#131] opened 2024-02-19 18:22 UTC
Shell.log output is as follows :-

`(metacity:911): metacity-WARNING **: 16:47:00.973: Option “--no-composite” is deprecated, use the “--compositor” instead.`
`1708106912.260464 ERROR root: set_active() failed: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`1708107106.669935 ERROR root: set_active() failed: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`1708118045.395503 WARNING root: no data for selection target MULTIPLE.`
`1708118045.433662 WARNING root: no data for selection target NULL.`
`1708118200.370356 ERROR root: set_active() failed: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`1708118326.579868 WARNING root: no data for selection target MULTIPLE.`
`1708118326.752622 WARNING root: no data for selection target NULL.`
`1708118331.591342 ERROR root: set_active() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "SetActive" with signature "v" on interface "org.laptop.Activity" doesn't exist`
`1708123067.050076 ERROR root: set_active() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "SetActive" with signature "v" on interface "org.laptop.Activity" doesn't exist`
`1708123100.975382 ERROR root: set_active() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "SetActive" with signature "v" on interface "org.laptop.Activity" doesn't exist`
`(metacity:911): metacity-WARNING **: 23:58:16.588: last_user_time (1708127896) is greater than comparison timestamp (25927958). This most likely represents a buggy client sending` `inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW. Trying to work around...`
`(metacity:911): metacity-WARNING **: 23:58:16.589: 0xe00008 (Chat Activity) appears to be one of the offending windows with a timestamp of 1708127896. Working around...`
`1708128011.038285 ERROR root: set_active() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "SetActive" with signature "v" on interface "org.laptop.Activity" doesn't exist`
`1708128503.737323 ERROR root: set_active() failed: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`1708128648.528195 ERROR root: set_active() failed: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`1708128662.573229 ERROR root: set_active() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "SetActive" with signature "v" on interface "org.laptop.Activity" doesn't exist`
`1708130354.515040 ERROR root: set_active() failed: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`1708130769.544480 ERROR root: set_active() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "SetActive" with signature "v" on interface "org.laptop.Activity" doesn't exist`
`1708130825.498344 ERROR root: set\_active() failed: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`1708130941.984615 WARNING root: no data for selection target MULTIPLE.`
`1708130942.029909 WARNING root: no data for selection target NULL.`
`1708131067.593885 WARNING root: no data for selection target MULTIPLE.`
`1708131067.625198 WARNING root: no data for selection target NULL.`
```1708131210.831571 ERROR dbus.proxies: Introspect error on :1.101:/org/laptop/Activity/e9cbd28d293d0bef922990befae41d91f7f10aa3:` dbus.exceptions.DBusException:``org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying```
`1708131210.851485 ERROR root: set\_active() failed: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.101 was not provided by any .service files`
`1708131254.315188 ERROR root: set\_active() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "SetActive" with signature "v" on interface "org.laptop.Activity" doesn't exist`
`1708131293.058005 ERROR dbus.proxies: Introspect error on :1.107:/org/laptop/Activity/30d6414cd2e3af6f61fc469617f922687ce2232b: dbus.exceptions.DBusException:`
`org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`1708131293.074493 ERROR root: set_active() failed: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.107 was not provided by any .service files`
`1708131304.239895 ERROR dbus.proxies: Introspect error on :1.111:/org/laptop/Activity/e17c417cb583eba9a7c5bfc064c75ccb38d27c88: dbus.exceptions.DBusException:` `org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`1708131304.265103 ERROR root: set_active() failed: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.111 was not provided by any .service files`
`1708131457.239108 ERROR root: set_active() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "SetActive" with signature "v" on interface "org.laptop.Activity" doesn't exist`

**Comment by quozl** [comment] 2024-02-19 19:31
Browse activity does not write to shell.log, please look for the activity log file in the same directory.  If there is no activity log, use the Terminal activity to test the Browse activity by hand;

```
cd /usr/share/sugar/activities/Browse.activity
sugar-activity3
```

**Comment by Ovalelephant35** [comment] 2024-02-19 21:44
i can see web-activity in the same directory are you talking about it?
then its says:-
failed to create drawable 1708378121.796552 : Error  root: WebView at uri 'https://github.com/Ovalelephant35' has crashed

**Comment by quozl** [comment] 2024-02-20 00:02
Thanks, that's interesting.  Your system is broken.  Let's see if we can fix it.  I suggest looking at the installed files for the libwebkit2gtk package, find the one called MiniBrowser, which on a 64-bit PC is /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser but will be different path on Raspberry Pi, run the MiniBrowser program, and use it to verify that the WebView is working properly.

Here's what I did on a PC;

```
dpkg-query -W | grep -i webkit
dpkg --listfiles libwebkit2gtk-4.0-37
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser 
```

If the MiniBrowser loads web pages fine, then the Browse activity may be bit rot.  If the MiniBrowser does not load web pages fine, please fix the problem before coming back to ask about Browse.  :grin:

**Comment by Ovalelephant35** [comment] 2024-02-23 23:31
MiniBrowser is loading webpages fine , how should i proceed then.

**Comment by quozl** [comment] 2024-02-24 03:43
Capture the activity log.

**Comment by Ovalelephant35** [comment] 2024-02-24 22:43
I tried again by rebooting Sugar and RPi and running minibrowser as stated above with including path etc on Rpi 
On terminal its is prompting 
`Failed to Created Drawable` while trying to run minibrowser.

**Comment by quozl** [comment] 2024-02-25 00:08
Okay, so you said
* the MiniBrowser opens your web page fine, and also says "Failed to create drawable",
* the Browse activity does not open your web page, and also says "Failed to create drawable", as well as "WebView at uri has crashed".

I suggest looking through the MiniBrowser source code and compare it to Browse activity, to find out what MiniBrowser does that Browse does not, or does differently.

**Comment by quozl** [comment] 2024-02-25 00:14
What version of the Browse activity?

**Comment by Ovalelephant35** [comment] 2024-02-25 16:42
Thanks for replying  , I am using version 206 for browser , ok let me compare both of the codes and see what is difference also i wanted to ask minibrowser only opens this site `webkitgtk.org`?

**Comment by quozl** [comment] 2024-02-26 05:40
> Thanks for replying , I am using version 206 for browser , 

Please upgrade to Browse 208 and test again.  Or, you might read the changes between 206 and 208 to see if any describe the problem you are facing.  See the commits to this repository, in whatever way you like.

> ok let me compare both of the codes and see what is difference also i wanted to ask minibrowser only opens this site `webkitgtk.org`?

Sorry, I can't parse your question.  Please try again.

> Also How can i access source code for minibrowser because the path `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser` does not contain it what is its location.

That's really outside scope for Browse activity, but https://github.com/WebKit/WebKit/blob/main/Tools/MiniBrowser/gtk/main.c is likely to be the upstream source code file.  The exact source for the exact version you have installed is best obtained using the Debian tools for downloading the packaged source; this is documented by Debian project, but it boils down to adding sources lines to your /etc/apt/sources.list file, doing an apt update, then an apt source command.

**Comment by Ovalelephant35** [comment] 2024-02-26 17:08
Yes upgradation to v208 worked as of now.

**Comment by quozl** [comment] 2024-02-27 05:09
Thanks.  We use upgrade rather than upgradation.  Now that the problem is fixed, I'll close the issue.

**Closed by quozl** 2024-02-27 05:09 UTC
