### ISSUE TITLE
Homepage file:// URL is downloaded (not shown)

### ISSUE THREAD

**Issue by jonassmedegaard** [sugarlabs/browse-activity#43] opened 2016-12-12 14:27 UTC
When starting Browse activity 200, default homepage URL gets downloaded, not rendered.

NB! I am testing Debian soon-to-be-in-unstable Browse package with only-in-unstable Sugar packages, so there is a real risk that I have missed some dependencies or broken something in the process of repackaging.

**Comment by jonassmedegaard** [comment] 2016-12-12 14:35
Maybe these emitted on console relate to this bug:

** (sugar-activity:5000): WARNING **: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined


(process:5009): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:5009): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:5009): GLib-GObject-CRITICAL **: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed
1481552389.831134 ERROR root: __download_requested_cb 'file:///usr/share/sugar/activities/Browse.activity/data/index.html'
1481552389.852234 ERROR root: gi.FunctionInfo(get_destination)
1481552389.858400 ERROR root: _create_journal_object
1481552390.069202 ERROR root: __download_finished_cb

**Comment by quozl** [comment] 2016-12-12 18:35
Doesn't reproduce for me with master on Ubuntu 16.04, so you might need a release after 200?

**Comment by City-busz** [comment] 2017-02-12 02:18
I experienced the same problem, but after I remove the ~/.local/share/mime directory, the problem solved. It happens with other webkit2gtk-based browsers too, so I think it's not a bug in browse-activity.

**Comment by quozl** [comment] 2017-05-29 07:46
Doesn't happen for me with Browse-201, closing.  Please re-open if reproduced.

**Closed by quozl** 2017-05-29 07:46 UTC
