### ISSUE TITLE
Paste of URL with a leading space does search Google

### ISSUE THREAD

**Issue by quozl** [sugarlabs/browse-activity#78] opened 2018-03-22 06:30 UTC
* visit any site,
* edit the URL to insert a leading space,
* press enter.

Expected result: same site is visited.

Observed result: Google Search is given the URL

**Comment by Pro-Panda** [comment] 2018-03-22 19:08
Unable to reproduce on Sugar 0.112, Ubuntu 16.04
Method used for testing: 
 - Open Browse activity
 - Visit www.github.com
 - Once loaded, add a leading space to the URL
 - Press enter

**Observed Result:**
the same site is visited

While trying to reproduce this, a strange issue observed was:
 - Visit www.sugarlabs.org
 - Edit the URL and type a new one
 - Press enter

**Expected Result:**
 - Redirected to the new URL

**Observed Result**
 - Redirected to www.sugarlabs.org/search/?q=

**Comment by quozl** [comment] 2018-03-26 01:01
I've no explanation for the observed difference in behaviour.

I've tested again, Browse 201.4 or d9eecc3e3cddbb08eecff7e0839bd43bc8bfd647, Sugar 0.112 on Ubuntu 16.04, in KVM;

* start Browse, and observe the default page `data/index.html',
* click in the URL entry widget, move insertion caret to start of entry, press space bar once, press enter,
* observe a Google Search is made instead.

![screenshot_ubuntu-xenial_2018-03-26_11 56 58](https://user-images.githubusercontent.com/2936481/37882199-d60cd932-30ec-11e8-81a3-0e0f1b9689fe.png)

Can you confirm you have latest version of WebKit2?  `dpkg-query -W | grep webkit` gives me `gir1.2-webkit2-4.0` version 2.18.6-0ubuntu0.16.04.1

On the additional problem you noted, I do observe that.  Astounding.

@geekrypter, you added the search feature to www.sugarlabs.org, how did you break Browse in this way?

**Comment by Pro-Panda** [comment] 2018-03-26 10:39
Able to reproduce.
Sorry. my mistake was that I was adding a trailing space.

**Comment by Pro-Panda** [comment] 2018-04-08 07:31
Fixed in 230a278

**Closed by Pro-Panda** 2018-04-08 07:31 UTC
